import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill, BsFillSunFill} from 'react-icons/bs';
import {AiFillGithub, AiFillInstagram, AiFillFacebook, AiOutlineGooglePlus} from 'react-icons/ai';
import image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import skl1 from "../public/skl1.jpg";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false) ;
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Bima Mahendra Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800'>
      <section className='min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons dark:text-white'>DevBimzz</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer dark:text-white'/>
            </li>
            <li>
              <a href="#" className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white py-2 px-4 rounded-md ml-8'>Resume</a>
            </li>
          </ul>
        </nav>
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-500 font-medium md:text-6xl'>Bima Mahendra</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Web Designer & Hackintosher</h3>
          <p className='text-md py-2 leading-8 text-gray-500 dark:text-gray-200'>Saya adalah seseorang yang mencintai program dan juga desain, saya menguasai beberapa bahasa pemrograman antara lain HTML, JS, PHP,MySQLi Dll. Saya juga termasuk Hackintosher Indonesia, Hackintosh sendiri adalah penggabungan antara Macintosh dan Hack, Lebih singkatnya adalah menjalankan Operasional Sistem Apple di non perangkat Apple</p>
        </div>
        <div className='text-5xl flex justify-center gap-10 text-gray-600'>
          <AiOutlineGooglePlus/>
          <AiFillFacebook/>
          <AiFillInstagram/>
          <AiFillGithub/>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden mb-10'>
          <Image src={deved} layout="fill" objectFit="cover" alt={''}/>
        </div>
      </section>
      <section>
        <div>
          <h3 className='text-3xl py-3 mt-5 dark:text-white'>Layanan Yang Saya Tawarkan</h3>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt eum expedita excepturi sed quod esse autem repellendus veniam at nisi! <span className='text-teal-500'>coabasad</span> Lorem ipsum dolor sit amet <span className='text-teal-500'>coabasad</span> Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt eum expedita excepturi sed quod esse autem repellendus veniam at nisi!</p>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat, esse est? Quas expedita dolorem repellat obcaecati quibusdam veritatis magni ratione.</p>
        </div>
        <div className='lg:flex gap-10'>
          <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
            <div className='flex justify-center'>
              <Image src={design} width={100} height={100} alt={''} />
            <h3 className='text-4xl font-medium pt-8 pb-2 ml-5 dark:text-white'>Hackintosher</h3>
            </div>
            <p className='py-2 dark:text-gray-300'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium, ex ipsam numquam asperiores incidunt nam reprehenderit iure consequuntur harum et?</p>
            <h4 className='py-4 text-teal-600'>Software yang saya gunakan</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Balena Eacher</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>MaciASL</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>PlistEditor Pro</p>
          </div>
          <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
            <div className='flex justify-center'>
              <Image src={code} width={100} height={100} alt={''} />
            <h3 className='text-4xl font-medium pt-8 pb-2 ml-5 dark:text-white'>Web Designer</h3>
            </div>
            <p className='py-2 dark:text-gray-300'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium, ex ipsam numquam asperiores incidunt nam reprehenderit iure consequuntur harum et?</p>
            <h4 className='py-4 text-teal-600'>Software yang saya gunakan</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Balena Eacher</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>MaciASL</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>PlistEditor Pro</p>
          </div>
          <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
            <div className='flex justify-center'>
              <Image src={consulting} width={100} height={100} alt={''} />
            <h3 className='text-4xl font-medium pt-8 pb-2 ml-5 dark:text-white'>Konsultasi</h3>
            </div>
            <p className='py-2 dark:text-gray-300'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium, ex ipsam numquam asperiores incidunt nam reprehenderit iure consequuntur harum et?</p>
            <h4 className='py-4 text-teal-600'>Software yang saya gunakan</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Balena Eacher</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>MaciASL</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>PlistEditor Pro</p>
          </div>
        </div>
      </section>
      <section>
        <div>
          <h3 className='text-3xl py-1 dark:text-white'>Portofolio</h3>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt eum expedita excepturi sed quod esse autem repellendus veniam at nisi! <span className='text-teal-500'>coabasad</span> Lorem ipsum dolor sit amet <span className='text-teal-500'>coabasad</span> Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt eum expedita excepturi sed quod esse autem repellendus veniam at nisi!</p>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat, esse est? Quas expedita dolorem repellat obcaecati quibusdam veritatis magni ratione.</p>
        </div>
        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
          <div className='basis-1/3 flex-1 shadow-2xl'>
            <Image src={web1} alt={''} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1 shadow-2xl'>
            <Image src={web2} alt={''} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1 shadow-2xl'>
            <Image src={web3} alt={''} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1 shadow-2xl'>
            <Image src={web4} alt={''} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1 shadow-2xl'>
            <Image src={web5} alt={''} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1 shadow-2xl'>
            <Image src={web6} alt={''} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
          </div>
        </div>
      </section>
      </main>

    </div>
  )
}
